service: aws-auth0-protected-endpoints

provider:
  name: aws
  runtime: nodejs4.3

functions:
  auth:
    handler: handler.auth
    environment:
      authId : ${file(env.yml):authId };
      authSecret: ${file(env.yml):authSecret };
  publicEndpoint:
    handler: handler.publicEndpoint
    events:
      - http:
          path: api/public
          method: get
          integration: lambda
          cors: true
  privateEndpoint:
    handler: handler.privateEndpoint
    events:
      - http:
          path: api/private
          method: get
          integration: lambda
          authorizer: auth
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
     